### ISSUE TITLE
pip install is not correct in documentation

### ISSUE THREAD

**Issue by stuchalk** [lmhale99/pycdcs#1]
In the documentation the pip install command is 'pip install pycdcs'.  This does not work.  However, 'pip install cdcs' does work.  Please update the documentation.  Also, why are there two repos for pycdcs?  Which one is official?  I would like to make sure I am using the correct and most up to date version.

Stuart Chalk
NIST Associate

**Comment by lmhale99** [comment]
Thanks for letting me know about this.  I've updated the README.

I wrote the README when it was meant to be pycdcs, but I had cdcs in the setup.py file, so it became cdcs in pip.  I just missed seeing that it still said pycdcs until now.  

The usnistgov repository gets updated when the official versions are released, while my personal lmhale99 repository is where I push working developments.  This package is relatively simple overall, so its unlikely that the two would ever deviate by much or for long.

Let me know if you run into any other issues or see something to add.

Lucas Hale

**Comment by stuchalk** [comment]
Lucas

Thanks for the update.  I can get the Python notebook (CDCS Public Data Exploration) to work in Jupyter
but I can’t get it to run in Python 3.8, 3.9, 3.10 - see below.  Anything thoughts?

[cid:E228D9EB-E27F-421D-AB83-B97CCEEEE132]

Stuart

On Feb 7, 2022, at 8:06 AM, Lucas Hale ***@***.******@***.***>> wrote:



Thanks for letting me know about this. I've updated the README.

I wrote the README when it was meant to be pycdcs, but I had cdcs in the setup.py file, so it became cdcs in pip. I just missed seeing that it still said pycdcs until now.

The usnistgov repository gets updated when the official versions are released, while my personal lmhale99 repository is where I push working developments. This package is relatively simple overall, so its unlikely that the two would ever deviate by much or for long.

Let me know if you run into any other issues or see something to add.

Lucas Hale

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmhale99%2Fpycdcs%2Fissues%2F1%23issuecomment-1031448365&data=04%7C01%7Cschalk%40unf.edu%7C953f6be8d8424124012b08d9ea3aa9f9%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798359952759243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p1dbKgZQXT%2FWsj2zlnMn2NFjTU4sjHg3lIOeCG0eCHg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAED35UX4U257JJQLPSNIE3UZ67VRANCNFSM5NS6J6QA&data=04%7C01%7Cschalk%40unf.edu%7C953f6be8d8424124012b08d9ea3aa9f9%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798359952759243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TOXZjnKt7POA96A6JaFgidoXhNsfqzj4vvrS4ecmmxE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cschalk%40unf.edu%7C953f6be8d8424124012b08d9ea3aa9f9%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798359952759243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W5BOnu9k6EETffIpxJMvfFfpj0qADt5eCBqdbWZ3wTs%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cschalk%40unf.edu%7C953f6be8d8424124012b08d9ea3aa9f9%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798359952759243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WhZRjowXOU0M7XMQk%2BeQrAi83g3nB%2FYDJ97HMJUm0I0%3D&reserved=0>.

**Comment by lmhale99** [comment]
Stuart,

I'm not seeing any details below?  Is there an error message during install, import, etc?

I just tested on a fresh 3.9 conda environment where all I did was "conda install cdcs -c conda-forge" after creating it.  The commands in the Notebook worked fine for me copying them into a Python terminal.

The only issue I saw was it was conda installed cdcs version 0.1.5 instead of 0.1.6, which should be fixed now or in the next hour or so when conda-forge rebuilds.

Lucas

**Comment by stuchalk** [comment]
Sorry, I must have forgotten add the picture.

Stuart

[cid:0A0F18E5-C20B-4547-8BC8-1D029C447044]

On Feb 7, 2022, at 1:10 PM, Lucas Hale ***@***.******@***.***>> wrote:



Stuart,

I'm not seeing any details below? Is there an error message during install, import, etc?

I just tested on a fresh 3.9 conda environment where all I did was "conda install cdcs -c conda-forge" after creating it. The commands in the Notebook worked fine for me copying them into a Python terminal.

The only issue I saw was it was conda installed cdcs version 0.1.5 instead of 0.1.6, which should be fixed now or in the next hour or so when conda-forge rebuilds.

Lucas

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmhale99%2Fpycdcs%2Fissues%2F1%23issuecomment-1031765280&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OM7YBAmhstXXgM7BMUqUe70m1Mk2vpR0yWDDhTWRXgs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAED35S24LI3E5FAZL6QFUTU2ADJPANCNFSM5NS6J6QA&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XKDTerhwYcXnu5d7f24rzh6hCUCjOxb1OE61sdw5Exk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gMG6faOhvjLMyJEJwWNEZhDkG8PlaErqJw7NLnkymOA%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hZ473rcUum%2BIBc%2BlpdA%2BUnxbpLGcLXE3K0bb3F6Nu%2B4%3D&reserved=0>.

**Comment by stuchalk** [comment]
Lucas

Sorry, the issue with the file not running was on my end.
I can confirm that the code works on Python 3.10.2.

Have you thought about adding continuous integration?

Stuart

On Feb 7, 2022, at 1:10 PM, Lucas Hale ***@***.******@***.***>> wrote:



Stuart,

I'm not seeing any details below? Is there an error message during install, import, etc?

I just tested on a fresh 3.9 conda environment where all I did was "conda install cdcs -c conda-forge" after creating it. The commands in the Notebook worked fine for me copying them into a Python terminal.

The only issue I saw was it was conda installed cdcs version 0.1.5 instead of 0.1.6, which should be fixed now or in the next hour or so when conda-forge rebuilds.

Lucas

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmhale99%2Fpycdcs%2Fissues%2F1%23issuecomment-1031765280&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OM7YBAmhstXXgM7BMUqUe70m1Mk2vpR0yWDDhTWRXgs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAED35S24LI3E5FAZL6QFUTU2ADJPANCNFSM5NS6J6QA&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XKDTerhwYcXnu5d7f24rzh6hCUCjOxb1OE61sdw5Exk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gMG6faOhvjLMyJEJwWNEZhDkG8PlaErqJw7NLnkymOA%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cschalk%40unf.edu%7Cd20a7341e13140ff582d08d9ea65210e%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637798542330256276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hZ473rcUum%2BIBc%2BlpdA%2BUnxbpLGcLXE3K0bb3F6Nu%2B4%3D&reserved=0>.

**Comment by lmhale99** [comment]
I haven't looked at continuous integration yet and don't have any experience with it, so I'd have to figure out where to start. It might be overkill for this project, but adding it here could be good practice for my other projects.

The other main bit is creating a full set of code evaluation tests in something like pytest.  It's something I want to and should do, I just have little patience for actually doing it.

**Comment by lmhale99** [comment]
I just uploaded a new version of the code.  Mostly, it adds Python typing hints for the functions and tests.  With the tests, continuous integration could be feasible now.

**Comment by stuchalk** [comment]
Lucas

Thanks for the update!

Stuart

On Mar 31, 2022, at 3:05 PM, Lucas Hale ***@***.******@***.***>> wrote:



I just uploaded a new version of the code. Mostly, it adds Python typing hints for the functions and tests. With the tests, continuous integration could be feasible now.
